apiVersion: apps/v1
kind: Deployment
metadata:
  name: javaapp-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: javaapp
  template:
    metadata:
      labels:
        app: javaapp
    spec:
      containers:
        - name: javaapp
          image: 842108/javaapp:20251021-1205
          ports:
            - containerPort: 8080
