apiVersion: apps/v1
kind: Deployment
metadata:
  name: javaapp-deployment
spec:
  replicas: 2
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: javaapp
  template:
    metadata:
      labels:
        app: javaapp
    spec:
      containers:
        - name: javaapp
          image: javaapp:build-20251024-1224
          ports:
            - containerPort: 8080
