
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: javaapp-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/vrajurkar95/javaapp-k8s-manifests.git
    targetRevision: HEAD
    path: helm/argocd
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
